{{- $fullName := include "kruize.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-config
  namespace: {{ .Release.Namespace }}
data:
  dbconfigjson: |
    {
      "database": {
        "adminPassword": {{ .Values.db.adminPassword | quote }},
        "adminUsername": {{ .Values.db.adminUser | quote }},
        "hostname": "{{ $fullName }}-db-service",
        "name": {{ if .Values.db.includeReleaseNameInDbName }}{{ printf "%s-%s" .Values.db.name $fullName | quote }}{{ else }}{{ .Values.db.name | quote }}{{ end }},
        "password": {{ .Values.db.password | quote }},
        "port": {{ .Values.db.service.port | quote }},
        "sslMode": {{ .Values.db.sslMode | quote }},
        "username": {{ .Values.db.user | quote }}
      }
    }
  kruizeconfigjson: |
    {
      "clustertype": {{ .Values.kruize.config.clusterType | quote }},
      "k8stype": {{ .Values.kruize.config.k8sType | quote }},
      "authtype": {{ .Values.kruize.config.authType | quote }},
      "monitoringagent": {{ .Values.kruize.config.monitoringAgent | quote }},
      "monitoringservice": {{ .Values.kruize.config.monitoringService | quote }},
      "monitoringendpoint": {{ .Values.kruize.config.monitoringEndPoint | quote }},
      "savetodb": {{ .Values.kruize.config.saveToDB | quote }},
      "dbdriver": {{ .Values.kruize.config.dbDriver | quote }},
      "plots": {{ .Values.kruize.config.plots | quote }},
      "isROSEnabled": {{ .Values.kruize.config.isROSEnabled | quote }},
      "local": {{ .Values.kruize.config.local | quote }},
      "logAllHttpReqAndResp": {{ .Values.kruize.config.logAllHttpReqAndResp | quote }},
      "recommendationsURL" : {{ printf "http://%s.%s.svc.cluster.local:8080/generateRecommendations?experiment_name=%%s" $fullName .Release.Namespace | quote }},
      "experimentsURL" : {{ printf "http://%s.%s.svc.cluster.local:8080/createExperiment" $fullName .Release.Namespace | quote }},
      "experimentNameFormat" : {{ .Values.kruize.config.experimentNameFormat | quote }},
      "bulkapilimit" : {{ .Values.kruize.config.bulkapilimit | quote }},
      "isKafkaEnabled" : {{ .Values.kruize.config.isKafkaEnabled | quote }},
      "hibernate": {
        "dialect": {{ .Values.kruize.config.hibernate.dialect | quote }},
        "driver": {{ .Values.kruize.config.hibernate.driver | quote }},
        "c3p0minsize": {{ .Values.kruize.config.hibernate.c3p0minsize | quote }},
        "c3p0maxsize": {{ .Values.kruize.config.hibernate.c3p0maxsize | quote }},
        "c3p0timeout": {{ .Values.kruize.config.hibernate.c3p0timeout | quote }},
        "c3p0maxstatements": {{ .Values.kruize.config.hibernate.c3p0maxstatements | quote }},
        "hbm2ddlauto": {{ .Values.kruize.config.hibernate.hbm2ddlauto | quote }},
        "showsql": {{ .Values.kruize.config.hibernate.showsql | quote}},
        "timezone": {{ .Values.kruize.config.hibernate.timezone | quote }}
      },
      "logging" : {
        "cloudwatch": {
          "accessKeyId": {{ .Values.kruize.config.logging.cloudwatch.accessKeyId | quote }},
          "logGroup": {{ .Values.kruize.config.logging.cloudwatch.logGroup | quote }},
          "logStream": {{ .Values.kruize.config.logging.cloudwatch.logStream | quote }},
          "region": {{ .Values.kruize.config.logging.cloudwatch.region | quote }},
          "secretAccessKey": {{ .Values.kruize.config.logging.cloudwatch.secretAccessKey | quote }},
          "logLevel": {{ .Values.kruize.config.logging.cloudwatch.logLevel | quote }}
        }
      },

      "datasource": [
       {{- range $index, $element := .Values.kruize.config.datasource }}
         {{- if $index }},{{ end }}
         {
           "name": {{ $element.name | quote }},
           "provider": {{ $element.provider | quote }},
           "serviceName": {{ $element.serviceName | quote }},
           "namespace": {{ $element.namespace | quote }},
           "url": {{ $element.url | quote }},
           "authentication": {
              "type": {{ $element.authentication.type | quote }},
              "credentials": {
                 "tokenFilePath": {{ $element.authentication.credentials.tokenFilePath | quote }}
               }
            }
          }
        {{- end }}
      ]
    }
