{{- $fullName := include "kruize.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
  labels:
    {{- include "kruize.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kruize.service.type }}
  selector:
    {{- include "kruize.selectorLabels" . | nindent 4 }}
  ports:
    - name: kruize-port
      port: {{ .Values.kruize.service.port }}
      targetPort: {{ .Values.kruize.service.port }}

