{{- $fullName := include "kruize.fullname" . -}}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $fullName }}-ui-nginx-pod
  namespace: {{ .Release.Namespace }}
  labels:
    app: kruize-ui-nginx
spec:
  containers:
    - name: kruize-ui-nginx-container
      image: "{{ .Values.kruizeUI.image.repository }}:{{ .Values.kruizeUI.image.tag }}"
      imagePullPolicy: {{ .Values.kruizeUI.image.pullPolicy }}
      env:
        - name: KRUIZE_UI_ENV
          value: "production"
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
  volumes:
    - name: nginx-config-volume
      configMap:
        name: {{ $fullName }}-nginx-config
