{{- $fullName := include "kruize.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kruize.deploymentName" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruize.labels" . | nindent 4 }}
    app: {{ $fullName }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kruize.selectorLabels" . | nindent 6 }}
      app: {{ $fullName }}-db
  template:
    metadata:
      labels:
	{{- include "kruize.selectorLabels" . | nindent 8 }}
        app: {{ $fullName }}-db
    spec:
      serviceAccountName: {{ include "kruize.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user | quote }}
            - name: POSTGRES_DB
              value: {{ printf "%s-%s" .Values.db.name $fullName | quote }}
            {{- if .Values.db.pgData }}
            - name: PGDATA
              value: {{ .Values.db.pgData }}
            {{- end }}
          {{- if or .Values.db.resources.requests.memory .Values.db.resources.requests.cpu .Values.db.resources.limits.memory .Values.db.resources.limits.cpu }}
          resources:
            {{- if or .Values.db.resources.requests.memory .Values.db.resources.requests.cpu }}
            requests:
              {{- if .Values.db.resources.requests.memory }}
              memory: {{ .Values.db.resources.requests.memory | quote }}
              {{- end }}
              {{- if .Values.db.resources.requests.cpu }}
              cpu: {{ .Values.db.resources.requests.cpu | quote }}
              {{- end }}
            {{- end }}
            {{- if or .Values.db.resources.limits.memory .Values.db.resources.limits.cpu }}
            limits:
              {{- if .Values.db.resources.limits.memory }}
              memory: {{ .Values.db.resources.limits.memory | quote }}
              {{- end }}
              {{- if .Values.db.resources.limits.cpu }}
              cpu: {{ .Values.db.resources.limits.cpu | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.db.service.port }}
          volumeMounts:
            - name: kruize-db-storage
              mountPath: {{ .Values.db.volumeMountPath }}
      volumes:
        - name: kruize-db-storage
          persistentVolumeClaim:
            claimName: {{ $fullName }}-db-pv-claim
