{{- $fullName := include "kruize.fullname" . -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-db-pv-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $fullName }}-db
spec:
  storageClassName: {{ .Values.db.pvc.storageClass | quote }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.db.pvc.storageSize | quote }}
